### ISSUE TITLE
Lacking Updated Champ List

### ISSUE THREAD

**Issue by Nick-Trot** [mattskrobola/OWV#1]
Hello,

This is currently missing some of the newer champions (Overwatch characters)

Please add the newest ones and some highlight clips to help me improve.

Thanks,

@mattskrobola `Nick-Trot`

**Comment by mattskrobola** [comment]
Hello @Nick-Trot ,

Unfortunately, this project has no plans for updates in the near future.
Feel free to make a pull request if you have any interest in contributing.
